channels:
  - conda-forge
  - nodefaults

dependencies:
  - altair==4.1.0
  - matplotlib==3.4.1
  - pandas==1.2.2
  - python==3.7.10 # This is what streamlit sharing uses
  - scikit-learn==0.24.1
  - seaborn==0.11.1
  - shap==0.39.0
  - streamlit==0.81.1
