# additional dependencies for dev container
channels:
  - conda-forge
  - nodefaults

dependencies:
  - altair==4.1.0
  - matplotlib==3.4.1
  - pandas==1.2.2
  - scikit-learn==0.24.1
  - seaborn==0.11.1
  - streamlit==0.81.1
